class_name UiText
extends RefCounted

const DEFAULT_LOCALE := "ko"

const KO := {
	"brand.title": "Luck Roulette",
	"brand.title_caps": "LUCK ROULETTE",
	"title.tagline": "뼈 주사위, 표식 구슬, 비뚤어진 룰렛 한 판.",
	"title.seed": "런 시드  {seed}",
	"title.motto": "생명력은 목숨이고, 골드는 협상이다.",
	"title.start": "테이블에 앉기",
	"title.new_run": "새 런 시작",
	"title.continue": "이어하기",
	"title.no_save": "저장 없음",
	"title.gallery": "도감",
	"title.settings": "설정",
	"title.quit": "종료",
	"title.disabled_hint": "준비 중",
	"title.route_note": "하우스가 오늘의 길을 펼쳐 두었다.",
	"intro.title": "자리에 앉는 중",
	"intro.subtitle": "하우스가 이번 런의 길을 펼친다.",
	"intro.progress": "패를 놓는 중",
	"run_end.clear_title": "런 클리어",
	"run_end.fail_title": "런 실패",
	"run_end.clear_subtitle": "마지막 하우스 테이블이 접혔다. 장부가 봉인된다.",
	"run_end.fail_subtitle": "테이블이 대가를 거두었다. 이번 장부는 여기서 닫힌다.",
	"run_end.final_hp": "최종 HP {hp}/{max_hp}",
	"run_end.gold": "골드 {gold}",
	"run_end.relics": "유물 {count}  {summary}",
	"run_end.nodes_cleared": "통과한 노드 {count}",
	"run_end.last_table": "마지막 테이블 {name}",
	"run_end.winnings": "전투 보상 {amount}",
	"run_end.stats.battle_line": "전투 {battles}  엘리트 {elites}  보스 {bosses}",
	"run_end.stats.route_line": "이벤트 {events}  상점 {shops}  휴식 {rests}",
	"run_end.stats.character_floor": "캐릭터 {character}  층 {floor}/{max_floor}",
	"run_end.stats.seed": "시드 {seed}",
	"run_end.stats.label.battles": "전투",
	"run_end.stats.label.nodes": "노드",
	"run_end.stats.label.route": "이벤트",
	"run_end.stats.label.gold": "골드",
	"run_end.character.default": "공격/방어",
	"run_end.character.double_attack": "쌍공격",
	"run_end.restart": "다시 앉기",
	"run_end.main_menu": "메인 테이블",
	"map.title": "행운 경로",
	"map.subtitle": "깔린 패, 더러운 길, 속여야 할 테이블",
	"map.ledger": "런 장부",
	"map.hp": "HP {hp}/{max_hp}",
	"map.gold": "골드 {gold}",
	"map.relics": "유물 {count}  {summary}",
	"map.next_mods": "다음 보정 {count}",
	"map.step": "{step}단계",
	"map.choose": "{label} 선택",
	"map.state.cleared": "완료",
	"map.state.current": "현재",
	"map.state.house": "하우스",
	"map.state.future": "대기",
	"map.node.combat": "전투",
	"map.node.elite": "엘리트",
	"map.node.event": "이벤트",
	"map.node.event.chest": "상자",
	"map.node.event.quest": "퀘스트",
	"map.node.event.gamble": "도박",
	"map.node.event.mystery": "미지",
	"map.node.shop": "상점",
	"map.node.rest": "휴식",
	"map.node.boss": "보스",
	"battle.action.rolling": "굴리는 중",
	"battle.action.roll": "굴리기",
	"battle.action.black_sword": "검 계약",
	"battle.action.black_shield": "방패 계약",
	"battle.action.black_roulette": "룰렛 계약",
	"battle.action.reroll": "다시 굴리기",
	"battle.action.push_dice": "Go",
	"battle.action.confirm": "Stop",
	"battle.action.spin": "돌리기",
	"battle.action.place_marble": "구슬 놓기",
	"battle.action.spinning": "도는 중",
	"battle.action.apply_result": "결과 적용",
	"battle.action.brace": "방어",
	"battle.action.take": "받기",
	"battle.action.ack": "확인",
	"battle.action.next_turn": "다음 턴",
	"battle.action.stop": "Stop",
	"battle.action.go": "Go",
	"battle.prompt.roll": "지금 할 일: 주사위를 굴린다",
	"battle.prompt.wager": "지금 할 일: 구슬 {committed}/{available}개, 판돈 {multiplier}",
	"battle.prompt.place_marble_after_dice": "지금 할 일: 구슬을 룰렛 칸에 놓는다",
	"battle.prompt.marble_landing": "지금 할 일: 구슬이 룰렛 칸에 놓이는 중이다",
	"battle.prompt.spin": "지금 할 일: 룰렛을 돌린다",
	"battle.prompt.choose_marble_slot": "지금 할 일: 구슬을 놓을 룰렛 칸을 고른다",
	"battle.prompt.wait_result": "지금 할 일: 결과를 기다린다",
	"battle.prompt.apply_result": "지금 할 일: 결과를 적용한다",
	"battle.prompt.enemy": "지금 할 일: 상대의 반격을 버티거나 그대로 받는다",
	"battle.prompt.run_over": "판이 끝났다. 새 판을 시작할 수 있다",
	"battle.prompt.next": "지금 할 일: 다음 행동으로 넘긴다",
	"battle.hud.hp": "HP {hp}/{max_hp}",
	"battle.hud.stake": "판돈 {amount}",
	"battle.hud.run": "런 {amount}",
	"battle.hud.turn": "{turn}턴",
	"battle.intent.damage": "다음 피해 {amount}",
	"battle.intent.guard": "다음 방어 {amount}",
	"battle.intent.attack_guard": "피해 {damage} + 방어 {block}",
	"battle.intent.buff": "다음 피해 +{amount}",
	"battle.intent.curse_weak": "다음 공격 -{amount}",
	"battle.intent.curse_weak_final": "다음 최종 피해 {percent}%",
	"battle.intent.curse_mark": "표식: 다음 피해 +{amount}",
	"battle.intent.curse_mark_double": "표식: 다음 피격 x{multiplier}",
	"battle.intent.tax": "골드 -{amount}",
	"battle.intent.attack_tax": "피해 {damage} + 골드 -{amount}",
	"battle.intent.disrupt": "다음 의도 숨김",
	"battle.intent.attack_disrupt": "피해 {damage} + 의도 숨김",
	"battle.intent.audit": "룰렛 감사",
	"battle.intent.appraise": "주사위 감정",
	"battle.intent.tithe": "방어 십일조",
	"battle.intent.hidden": "의도 불명",
	"battle.message.initial": "주사위 타임. 굴린 뒤 하나를 잠그고 다시 굴릴 수 있다.",
	"battle.message.encounter": "주사위 타임. 이번 전투의 자원부터 직접 만든다.",
	"battle.message.relics": " 유물: {relics}.",
	"battle.message.opponent": " 상대: {monster}.",
	"battle.message.start_mods": " 시작 보정 {count}개 적용.",
	"battle.message.double_attack_prompt": "메인 공격 주사위를 고른다. 다른 눈도 공격에 더해진다.",
	"battle.message.attack_guard_prompt": "공격에 쓸 주사위를 고른다. 남은 눈은 이번 턴 방어가 된다.",
	"battle.message.black_signer_prompt": "주사위 대신 서명할 계약을 고른다. 세 번째 빚 표식은 즉시 피해가 된다.",
	"battle.message.black_signer_sword": "검 계약에 서명했다. 공격 {attack}, 빚 {debt}/3.",
	"battle.message.black_signer_shield": "방패 계약에 서명했다. 공격 {attack}, 방어 {guard}, 빚 {debt}/3.",
	"battle.message.black_signer_roulette": "룰렛 계약에 서명했다. 공격 {attack}, 실패 재시도 +1, 빚 {debt}/3.",
	"battle.message.black_signer_debt_hit": "검은 빚이 세 칸 찼다. HP 6을 잃고 표식은 비워졌다.",
	"battle.message.double_attack_roll": "두 주사위를 굴렸다. 메인 공격 주사위를 고르면 두 눈이 모두 공격이 된다.",
	"battle.message.attack_guard_roll": "두 주사위를 굴렸다. 공격 주사위를 고르면 남은 눈이 방어가 된다.",
	"battle.message.double_attack_result": "주사위 결과 {values}. 메인 공격 주사위를 고르면 두 눈이 모두 공격이 된다.",
	"battle.message.attack_guard_result": "주사위 결과 {values}. 공격 주사위를 고르면 남은 눈이 방어가 된다.",
	"battle.message.click_spin": "중앙 룰렛을 클릭해 돌린다.",
	"battle.message.click_marble_slot": "강화할 룰렛 칸을 클릭해 구슬을 올린다.",
	"battle.message.dice_attack_ready": "주사위 눈금이 공격 기본값 {attack}이 됐다. 이제 구슬 하나로 룰렛에 실어 보낸다.",
	"battle.message.roll_single": "왼쪽 주사위 칸에서 굴렸다. 공격 기본값 {attack}. 다시 굴리거나 Stop.",
	"battle.message.reroll_choice": "다시 굴렸다. {prompt}",
	"battle.message.reroll_single": "열린 주사위만 다시 굴렸다. 공격 기본값 {attack}.",
	"battle.message.roll_cup": "컵 안에서 주사위를 흔든 뒤 배틀판 위로 굴리는 중이다.",
	"battle.message.roll_slot": "왼쪽 주사위 칸에서 주사위를 굴리는 중이다.",
	"battle.message.dice_result_single": "주사위 결과 {values}. 공격 기본값 {attack}. 다시 굴리거나 Stop.",
	"battle.message.dice_push_success": "{from}에서 {to}로 Go 성공. 공격 기본값 {attack}. 남은 Go {left}회.",
	"battle.message.dice_push_locked": "{from}에서 {to}로 Go 성공. 공격 기본값 {attack}. 이제 Stop.",
	"battle.message.dice_push_failed": "{from}에서 {to}로 Go 실패. 새 합의 절반으로 공격 기본값 {attack}.",
	"battle.message.extra_roll_choice": "한 번 더 굴렸다. {prompt}",
	"battle.message.extra_roll_single": "한 번 더 굴렸다. 공격 기본값 {attack}.",
	"battle.message.choose_attack_first": "먼저 공격에 쓸 주사위를 고른다.",
	"battle.message.marble_instruction": "룰렛 칸을 클릭하면 바로 구슬을 올린다. 버튼은 선택된 칸에 놓는 보조 조작이다.",
	"battle.message.marble_boost_slot": "{slot} 칸에 구슬을 올린다. 룰렛이 그 칸에 멈추면 {reward}.",
	"battle.message.marble_setup_done": "구슬이 룰렛 칸 하나를 강화했다. 이제 룰렛 전용 장면에서 진짜 결과를 본다.",
	"battle.message.die_lock": "주사위 {index} {state}.",
	"battle.message.locked": "잠금",
	"battle.message.unlocked": "잠금 해제",
	"battle.message.attack_guard_selected": "공격 {attack}, 방어 {guard}. 남은 눈이 방어로 올라갔다.",
	"battle.message.double_attack_selected": "공격 {attack}. 두 눈이 모두 공격으로 들어갔다.",
	"battle.message.marble_scene": "전용 배치 장면에서 구슬을 룰렛 칸에 직접 놓는다.",
	"battle.message.marble_slot_selected": "{slot} 칸에 구슬을 올린다. 아직 결과가 아니다. 다음에 룰렛을 돌린다.",
	"battle.message.marble_stored": "{marble} 구슬 하나를 다음 턴으로 킵했다.",
	"battle.message.marble_recalled": "킵해둔 구슬을 손으로 가져왔다. 바로 룰렛에 올릴 수 있다.",
	"battle.message.roulette_start": "테이블 중앙 룰렛이 돈다. 멈춘 칸의 배수가 이번 공격이 된다.",
	"battle.message.roulette_return": "룰렛 의식 결과가 전투판으로 돌아왔다. 공격 배율 x{multiplier}.",
	"battle.message.roulette_stopped": "룰렛이 멈췄다. 결과를 적용한다.",
	"battle.message.brake_success": "브레이크 성공. 실패를 명중으로 접었다.",
	"battle.message.brake_reduce": "브레이크로 실패를 피했다. 대신 피해 배율은 줄었다.",
	"battle.message.nudge_result": "룰렛을 한 칸 밀었다. 새 결과: {slot}",
	"battle.message.double_down": "더블다운. 공격 배율이 크게 오른다.",
	"battle.message.enemy_action": "{monster} 행동: {move}. 방어 {block}, 피해 {damage}.",
	"battle.message.turn_start": "주사위 타임. 이번 턴의 자원부터 직접 만든다.",
	"battle.message.cash_out": "전투를 빠져나와 수익을 확정했다.",
	"battle.message.marble_ready": "구슬이 룰렛 위에 올라갔다. 이제 중앙 룰렛을 돌린다.",
	"battle.message.wager_ready": "공격 {attack}. 전투 구슬 {available}개 중 몇 개를 걸지 정한다.",
	"battle.message.wager_changed": "구슬 {committed}개를 건다. 판돈 배율 {multiplier}.",
	"battle.message.numeric_roulette_start": "구슬 {committed}개를 잠갔다. 판돈 배율 {wager}. 룰렛이 돈다.",
	"battle.message.numeric_roulette_preview": "룰렛 {roulette}, 판돈 {wager}. 예상 피해 {damage}. 멈추거나 고를 수 있다.",
	"battle.message.numeric_go_result": "고 결과 {roulette}. 현재 피해 {damage}.",
	"battle.message.numeric_damage": "공격 {attack} x 룰렛 {roulette} x 판돈 {wager} = {damage} 피해.",
	"battle.banner.attack_marbles": "ATTACK {attack} / 구슬 x{count}",
	"battle.banner.wager": "판돈 정하기",
	"battle.banner.marble_setting": "구슬 세팅 중",
	"battle.banner.marble_count": "구슬 {count}개 세팅",
	"battle.banner.attack_guard": "공격 {attack} / 방어 {guard}",
	"battle.banner.attack_no_guard": "공격 {attack} / 방어 없음",
	"battle.banner.choose_attack_die": "주사위 선택",
	"battle.banner.dice_push_success": "Go 성공",
	"battle.banner.dice_push_failed": "Go 실패",
	"battle.banner.roulette_start": "룰렛 가동",
	"battle.banner.spin_ready": "이제 룰렛 돌리기",
	"battle.phase.dice": "주사위 차례",
	"battle.phase.wager": "판돈 정하기",
	"battle.phase.marble": "구슬 올리기",
	"battle.phase.spinning": "룰렛이 돈다",
	"battle.phase.intervene": "마지막 손대기",
	"battle.phase.enemy": "상대 차례",
	"battle.phase.win": "판돈을 땄다",
	"battle.phase.end": "판 종료",
	"battle.phase.result": "이번 턴 결과",
	"battle.die.left": "왼쪽",
	"battle.die.right": "오른쪽",
	"battle.die.main_attack": "메인 공격",
	"battle.die.attack": "공격",
	"battle.marble.plain": "공격",
	"battle.marble.yellow": "노랑 표식",
	"battle.marble.green": "초록 보상",
	"battle.marble.purple": "보라 잭팟",
	"battle.layer.multiplier": "배수",
	"battle.layer.click_roulette": "룰렛 클릭",
	"battle.layer.setup_done": "세팅 완료",
	"battle.layer.boosted": "강화",
	"battle.layer.rolling_in_cup": "컵에서 굴리는 중",
	"battle.layer.roll_lands_here": "결과가 나오면 이 칸에 놓인다",
	"battle.layer.dice_contract": "주사위 계약",
	"battle.layer.attack_value": "공격 {amount}",
	"battle.layer.guard_value": "방어 {amount}",
	"battle.layer.rerolls": "다시 {amount}",
	"battle.layer.attack_choice": "공격 선택",
	"battle.layer.reroll_confirm": "다시 {rerolls} / Stop",
	"battle.layer.attack_void": "실패: 공격 무효",
	"battle.layer.apply_result": "결과 적용",
	"battle.layer.bust": "실패",
	"battle.layer.reward_delta": "보상 {delta}",
	"battle.layer.marble_pouch": "구슬 주머니",
	"battle.layer.slot_boost_count": "슬롯 강화 x{count}",
	"battle.layer.shake_power": "흔드는 힘",
	"battle.layer.die_pips": "눈 {value}",
	"battle.layer.next": "다음",
	"battle.layer.damage": "피해 {amount}",
	"battle.caption.smirk": "상대가 웃는다",
	"battle.caption.hit": "상대가 흔들린다",
	"battle.caption.press": "상대가 공격을 준비한다",
	"battle.caption.watch": "상대가 판을 지켜본다",
	"roulette.slot.profit.label": "명중",
	"roulette.slot.profit.hint": "기본 배율",
	"roulette.slot.profit.banner": "명중",
	"roulette.slot.jackpot.label": "대박",
	"roulette.slot.jackpot.hint": "가장 높은 배율",
	"roulette.slot.jackpot.banner": "대박",
	"roulette.slot.bust.label": "실패",
	"roulette.slot.bust.hint": "공격이 빗나간다",
	"roulette.slot.bust.banner": "실패",
	"roulette.slot.overdrive.label": "강타",
	"roulette.slot.overdrive.hint": "높은 배율",
	"roulette.slot.overdrive.banner": "강타",
	"roulette.slot.safe.label": "명중",
	"roulette.slot.safe.hint": "기본 배율",
	"roulette.slot.safe.banner": "명중",
	"roulette.slot.profit.boost_label": "명중+",
	"roulette.slot.profit.boost_hint": "구슬이 놓여 배율이 오른다",
	"roulette.slot.profit.boost_banner": "강화 명중",
	"roulette.slot.jackpot.boost_label": "대박+",
	"roulette.slot.jackpot.boost_hint": "구슬이 놓여 최고 배율이 오른다",
	"roulette.slot.jackpot.boost_banner": "강화 대박",
	"roulette.slot.bust.boost_label": "실패 보호",
	"roulette.slot.bust.boost_hint": "구슬이 막아 실패가 명중으로 바뀐다",
	"roulette.slot.bust.boost_banner": "실패 보호",
	"roulette.slot.overdrive.boost_label": "강타+",
	"roulette.slot.overdrive.boost_hint": "구슬이 놓여 강타 배율이 오른다",
	"roulette.slot.overdrive.boost_banner": "강화 강타",
	"roulette.slot.safe.boost_label": "명중+",
	"roulette.slot.safe.boost_hint": "구슬이 놓여 배율이 오른다",
	"roulette.slot.safe.boost_banner": "강화 명중",
	"payout.bust": "룰렛 {label}. 공격이 막히고 추가 페널티가 적용됐다.",
	"payout.damage": "{boosted}공격 {attack} x{multiplier} = {damage} 피해.",
	"payout.boosted_prefix": "강화 칸! ",
	"payout.bonus": " 추가 보상 {delta}.",
	"payout.enemy_blocked": " 상대 방어가 {amount} 막았다.",
	"payout.curse_halved": " 저주로 {before}->{after}.",
	"settings.title": "설정",
	"settings.subtitle": "소리, 화면, 언어를 조정한다",
	"settings.master": "전체",
	"settings.bgm": "음악",
	"settings.sfx": "효과",
	"settings.fullscreen": "전체화면",
	"settings.fullscreen_on": "사용",
	"settings.language": "언어",
	"settings.language.ko": "한국어",
	"settings.language.en": "English",
	"settings.back": "뒤로",
	"gallery.title": "도감",
	"gallery.category.characters": "캐릭터",
	"gallery.category.relics": "유물",
	"gallery.category.monsters": "몬스터",
	"gallery.category.events": "이벤트",
	"gallery.subtitle.characters": "계약 캐릭터",
	"gallery.subtitle.relics": "런에서 발견할 수 있는 유물",
	"gallery.subtitle.monsters": "테이블에서 만나는 상대",
	"gallery.subtitle.events": "이벤트 기록",
	"gallery.locked.title": "잠긴 장",
	"gallery.locked.body": "아직 장부에 붙일 기록이 없다.",
	"gallery.undiscovered": "미발견",
	"gallery.status.locked": "잠김",
	"gallery.status.coming_soon": "준비 중",
	"gallery.status.needs_art": "아트 필요",
	"gallery.back": "뒤로",
	"pause.title": "일시정지",
	"pause.abandon_title": "런 포기",
	"pause.resume": "계속하기",
	"pause.return": "돌아가기",
	"pause.settings": "설정",
	"pause.main_menu": "메인 테이블",
	"pause.abandon": "런 포기",
	"pause.confirm_abandon": "포기 확정",
	"pause.phase.map": "길 위의 장부를 잠시 덮었다.",
	"pause.phase.combat": "전투 테이블을 잠시 멈췄다.",
	"pause.phase.reward": "보상 선택을 잠시 미뤘다.",
	"pause.phase.event": "이벤트 판단을 잠시 미뤘다.",
	"pause.phase.shop": "상점 거래를 잠시 멈췄다.",
	"pause.phase.rest": "휴식 선택을 잠시 미뤘다.",
	"pause.phase.default": "테이블을 잠시 멈췄다.",
	"pause.confirm_label": "현재 런 저장을 지우고 메인 테이블로 돌아간다.",
	"reward.title": "보상 전표",
	"reward.subtitle": "테이블 보상을 챙기고 이번 런의 물건 하나를 고른다.",
	"reward.subtitle.claim_all": "테이블이 정산한 보상을 모두 챙긴다.",
	"reward.winnings": "전투 보상 {amount}",
	"reward.claim": "청구",
	"reward.item.gold": "골드",
	"reward.item.gold.note": "기본 전투 정산금.",
	"reward.item.tickets": "티켓",
	"reward.item.tickets.note": "휴식 교환용 계약권.",
	"reward.item.heal": "응급 회복",
	"reward.item.heal.note": "낮은 확률의 작은 회복.",
	"reward.item.relic": "엘리트 유물",
	"reward.item.relic.note": "엘리트 전투 전용 유물.",
	"reward.choice.money.label": "골드 주머니",
	"reward.choice.money.note": "골드를 더 챙긴다.",
	"reward.choice.money.effect": "+{amount} 골드",
	"reward.choice.relic.label": "유물 청구",
	"reward.choice.relic.note": "런 유물 하나를 더한다.",
	"reward.choice.heal.label": "상처 꿰매기",
	"reward.choice.heal.note": "테이블 뒤 회복한다.",
	"reward.choice.heal.effect": "+{amount} HP",
	"rest.upgrade_hint": "룰렛 칸은 현재 값에 따라 강화권 1/2/3장, 룰렛은 1장, 주사위는 2장이 필요하다.",
	"rest.upgrade.vouchers": "보유 강화권 {count}장",
	"rest.upgrade.effect_cost": "{effect} / 강화권 {count}",
	"rest.upgrade.effect_free": "{effect} / 기본",
	"rest.upgrade.use_voucher": "강화권 사용 ({count})",
	"rest.upgrade.finish": "강화 완료",
	"rest.upgrade.ready_again": "강화권을 써서 한 번 더 고를 수 있다.",
	"rest.upgrade.pending_finish": "강화를 마치거나 강화권을 써서 한 번 더 고른다.",
	"rest.back": "뒤로",
	"rest.action.heal.label": "붕대 감기",
	"rest.action.heal.note": "상처를 꿰맨 뒤 휴식을 끝낸다.",
	"rest.action.tune.label": "판 조율",
	"rest.action.tune.note": "이번 런 동안 계속 남는 강화를 고른다.",
	"rest.action.tune.effect": "강화 선택",
	"rest.action.relic.label": "수상한 유물",
	"rest.action.relic.note": "덮인 물건 하나를 챙긴다.",
	"rest.action.relic.effect": "유물 +1",
	"rest.upgrade.primary.label": "메인 주사위 조율",
	"rest.upgrade.primary.short": "메인 주사위",
	"rest.upgrade.primary.note": "메인 주사위 해석 +1.",
	"rest.upgrade.primary.effect": "메인 +1",
	"rest.upgrade.secondary.label": "보조 주사위 조율",
	"rest.upgrade.secondary.short": "보조 주사위",
	"rest.upgrade.secondary.note": "보조 주사위 해석 +1.",
	"rest.upgrade.secondary.effect": "보조 +1",
	"rest.upgrade.roulette.label": "룰렛 조율",
	"rest.upgrade.roulette.note": "모든 룰렛 결과가 오른다.",
	"rest.upgrade.roulette.effect": "룰렛 +0.2x",
	"rest.upgrade.roulette_cell.label": "룰렛 칸 강화",
	"rest.upgrade.roulette_cell.note": "원하는 숫자 칸 하나를 다음 단계로 올린다.",
	"rest.upgrade.roulette_cell.effect": "칸별 강화권 1-3장",
	"rest.upgrade.roulette_cell.title": "룰렛 칸 강화",
	"rest.upgrade.roulette_cell.subtitle": "강화할 숫자 칸을 고른다. x0과 x3은 더 올릴 수 없다.",
	"rest.upgrade.roulette_cell.vouchers": "보유 강화권 {count}장",
	"rest.upgrade.roulette_cell.cost": "강화권 {count}장",
	"rest.upgrade.roulette_cell.max": "고정",
	"rest.exchange.open": "티켓 교환소",
	"rest.exchange.title": "티켓 교환소",
	"rest.exchange.subtitle": "휴식에서만 쓰는 계약권으로 물약과 작은 보급을 챙긴다.",
	"rest.exchange.tickets": "보유 티켓 {amount}",
	"rest.exchange.potions": "물약 슬롯 {used}/{max}",
	"rest.exchange.back_hint": "아직 교환하지 않았다. 뒤로 돌아갈 수 있다.",
	"rest.exchange.locked_back": "교환을 마쳤다. 나가면 휴식이 끝난다.",
	"rest.exchange.done": "교환 완료",
	"rest.exchange.small_heal.label": "응급 붕대",
	"rest.exchange.small_heal.note": "즉시 작은 회복.",
	"rest.exchange.small_heal.effect": "HP +5",
	"rest.exchange.random_potion.label": "랜덤 물약",
	"rest.exchange.random_potion.note": "물약 슬롯에 무작위 보급품을 넣는다.",
	"rest.exchange.random_potion.effect": "랜덤 물약 +1",
	"rest.exchange.upgrade_voucher.label": "강화권",
	"rest.exchange.upgrade_voucher.note": "반복 구매할 수 있는 조율권.",
	"rest.exchange.upgrade_voucher.effect": "강화권 +1",
	"rest.exchange.random_relic.label": "랜덤 유물",
	"rest.exchange.random_relic.note": "현재 캐릭터 풀에서 하나를 뽑는다.",
	"rest.exchange.random_relic.effect": "유물 +1",
	"rest.result.heal": "상처를 꿰맸다. +{amount} HP",
	"rest.result.relic": "덮인 유물을 챙겼다. {relic}",
	"rest.result.primary": "메인 주사위 조율 완료. 이번 런 동안 메인 해석 +1",
	"rest.result.secondary": "보조 주사위 조율 완료. 이번 런 동안 보조 해석 +1",
	"rest.result.roulette": "룰렛 조율 완료. 이번 런 동안 모든 결과 +0.2x",
	"rest.result.roulette_cell": "룰렛 칸 강화 완료. {from} -> {to}",
	"rest.result.exchange": "티켓 {tickets}장을 교환했다. 물약 +{potions}",
	"rest.result.done": "휴식 행동 완료.",
	"shop.confirm": "구매 확정",
	"shop.storage": "보관함",
	"shop.prep.label": "준비 표식",
	"shop.prep.note": "다음 전투 피해를 줄인다.",
	"shop.prep.effect": "다음 피해 -2",
	"shop.gold_price": "{amount} 골드",
	"shop.ticket_price": "{amount} 티켓",
	"shop.insufficient": "부족",
	"shop.detail.title": "상품 전표",
	"shop.detail.empty": "진열된 물건을 고른다.",
	"shop.detail.empty_note": "설명과 구입 버튼이 여기 열린다.",
	"shop.no_selection": "선택 없음",
	"shop.product_fallback": "상품",
	"shop.prep.description": "다음 전투 첫 피해를 줄인다.",
	"shop.visit_bought": "구매 {count}",
	"shop.reroll": "재진열",
	"shop.reroll_price": "{amount} 골드",
	"shop.service.soft_prep.label": "준비 표식",
	"shop.service.soft_prep.note": "다음 전투 피해를 줄인다.",
	"shop.service.soft_prep.effect": "다음 피해 -2",
	"shop.service.soft_prep.description": "다음 전투 첫 피해를 2 줄인다.",
	"shop.service.cash_bait.label": "현상금 미끼",
	"shop.service.cash_bait.note": "다음 판돈을 키운다.",
	"shop.service.cash_bait.effect": "다음 보상 +8",
	"shop.service.cash_bait.description": "다음 전투 보상 골드를 8 늘린다.",
	"shop.service.heal_vial.label": "붉은 치료약",
	"shop.service.heal_vial.note": "상처를 급히 봉합한다.",
	"shop.service.heal_vial.effect": "HP +8",
	"shop.service.heal_vial.description": "HP를 최대치 안에서 8 회복한다.",
	"shop.service.marble_polish.label": "구슬 광택제",
	"shop.service.marble_polish.note": "판돈 구슬을 다듬는다.",
	"shop.service.marble_polish.effect": "판돈 보정 +1",
	"shop.service.marble_polish.description": "이번 런 동안 건 구슬마다 판돈 보정이 오른다.",
	"shop.service.dice_tune.label": "주사위 손질",
	"shop.service.dice_tune.note": "메인 주사위를 다듬는다.",
	"shop.service.dice_tune.effect": "메인 해석 +1",
	"shop.service.dice_tune.description": "이번 런 동안 메인 주사위 해석이 1 오른다.",
	"shop.service.roulette_tune.label": "룰렛 조율",
	"shop.service.roulette_tune.note": "바퀴 눈금을 느슨하게 한다.",
	"shop.service.roulette_tune.effect": "결과 +0.2x",
	"shop.service.roulette_tune.description": "이번 런 동안 룰렛 결과 보정이 0.2 오른다.",
	"shop.service.risk_contract.label": "위험 계약",
	"shop.service.risk_contract.note": "보상과 위협이 같이 오른다.",
	"shop.service.risk_contract.effect": "보상 +14 / 피해 +2",
	"shop.service.risk_contract.description": "다음 전투 보상은 오르지만 적 피해도 2 오른다.",
	"shop.service.blood_discount.label": "피값 할인권",
	"shop.service.blood_discount.note": "피로 산 수상한 전표.",
	"shop.service.blood_discount.effect": "HP -3 / 보상 +10",
	"shop.service.blood_discount.description": "HP를 3 잃고 다음 전투 보상 골드를 10 늘린다.",
	"table.pickup.waiting": "선택 대기",
	"table.pickup.waiting_line": "카드를 고르면 결과가 장부나 트레이에 꽂힌다.",
	"table.pickup.gold_loss": "골드 {old} -> {new} ({delta})",
	"table.pickup.gold_gain": "골드 +{delta} -> {new}",
	"table.pickup.ticket_loss": "티켓 {old} -> {new} ({delta})",
	"table.pickup.ticket_gain": "티켓 +{delta} -> {new}",
	"table.pickup.hp_loss": "HP {old} -> {new}/{max} ({delta})",
	"table.pickup.hp_gain": "HP +{delta} -> {new}/{max}",
	"table.pickup.relic_added": "{relic} 획득",
	"table.pickup.prep": "준비: {description}",
	"table.pickup.potion_added": "물약: {potion}",
	"table.pickup.potion_removed": "소모: {potion}",
	"table.pickup.no_change": "변경 없음",
	"battle.action.potion": "물약",
	"battle.action.back": "돌아가기",
	"battle.message.potion.red": "빨간 물약: 직전 피해 {amount}을 회복했다.",
	"battle.message.potion.guard": "노란 방패 물약: 방어력 10을 얻었다.",
	"battle.message.potion.reward": "초록 물약: 승리 보상 확률이 2배가 된다.",
	"battle.message.potion.jackpot": "보라 번개 물약: 이번 전투 첫 잭팟 피해 +30.",
	"battle.message.potion.wager": "하얀 물약: 판돈 구슬 2개를 더 받았다.",
	"battle.message.potion.time": "청록 물약: Go 기회가 1회 늘었다.",
	"potion.red_recovery_potion": "빨간 회복 물약",
	"potion.reward_luck_potion": "초록 보상 물약",
	"potion.jackpot_potion": "보라 번개 물약",
	"potion.dice_potion": "파란 주사위 물약",
	"potion.time_potion": "청록 시간 물약",
	"potion.attack_potion": "공격 물약",
	"potion.guard_potion": "방어 물약",
	"potion.roulette_potion": "룰렛 물약",
	"potion.wager_potion": "판돈 물약",
	"potion.upgrade_voucher": "강화권",
	"table.choice.money": "골드 정산",
	"table.choice.relic": "유물 획득",
	"table.choice.heal": "회복 정산",
	"table.choice.shop_relic": "상점 유물",
	"table.choice.prep": "준비 쪽지",
	"table.choice.event_gold": "소문값 정산",
	"table.choice.event_relic_trade": "유물 거래",
	"table.choice.event_risk_gold": "뜨거운 거래",
	"table.choice.backroom_die_test": "뒷방 주사위",
	"table.choice.backroom_die_leave": "조용한 퇴장",
	"table.choice.crooked_wheel_bet": "비뚤어진 룰렛",
	"table.choice.crooked_wheel_leave": "룰렛 사양",
	"table.choice.sealed_side_box": "봉인된 전표",
	"table.choice.sealed_cards_leave": "상자 닫기",
	"table.choice.rest_heal": "휴식 회복",
	"table.choice.rest_leave": "휴식 종료",
	"table.choice.rest_ticket_exchange": "티켓 교환",
	"table.choice.ticket_random_potion": "랜덤 물약 교환",
	"table.choice.ticket_upgrade_voucher": "강화권 교환",
	"table.choice.ticket_small_heal": "붕대 교환",
	"table.choice.ticket_random_relic": "랜덤 유물 교환",
	"table.choice.combat_reward": "전투 보상",
	"table.choice.elite_reward": "엘리트 보상",
	"table.choice.result": "결과 정산",
	"table.prep.damage_up": "다음 피해 +{amount}",
	"table.prep.damage_down": "다음 피해 -{amount}",
	"table.prep.default": "다음 전투 쪽지",
	"overlay.exit": "나가기",
	"overlay.relics": "유물",
	"overlay.hp": "HP",
	"overlay.gold": "골드",
	"overlay.tickets": "티켓",
	"overlay.potions": "물약",
	"overlay.floor": "층",
	"overlay.settings": "설정",
	"overlay.empty": "비어 있음",
	"overlay.result_settled": "결과 정산",
	"overlay.relic_tray": "유물 트레이",
	"overlay.prep_notes": "준비 쪽지",
	"overlay.applied_notes": "적용 쪽지",
	"overlay.no_pending": "대기 없음",
	"character.select.title": "계약 선택",
	"character.select.hint": "카드를 눌러 계약을 살펴보고, 시작 버튼으로 확정한다",
	"character.select.selected": "선택됨",
	"character.select.confirm": "계약 시작",
	"character.starting_relic.label": "시작 유물",
	"ritual.enemy.default_intent": "상대가 다음 수를 노린다",
	"ritual.enemy.apply": "상대 행동 적용\n결과로",
	"ritual.resolution.default_message": "결과를 적용한다.",
	"ritual.resolution.formula": "주사위 공격값에 룰렛 배율을 곱해 피해를 적용한다",
	"ritual.resolution.return_note": "전투판으로 결과를 돌려보낸다",
	"ritual.resolution.apply": "결과 적용\n전투판으로",
	"event.fallback.title": "사건 전표",
	"event.story.show_choices": "선택지 보기",
	"event.story.next_slip": "다음 전표",
	"event.header.dice_title": "뒷방 주사위 판정",
	"event.header.dice_subtitle": "주사위 2개의 합이 목표값을 넘기면 성공한다.",
	"event.header.roulette_title": "비뚤어진 룰렛",
	"event.header.roulette_subtitle": "멈춘 칸대로 전표가 닫힌다.",
	"event.header.card_title": "봉인된 전표 뽑기",
	"event.header.card_subtitle": "한 장만 고른다. 뒤집힌 뒤 전표가 닫힌다.",
	"event.dice.great": "대성공",
	"event.dice.success": "성공",
	"event.dice.fail": "실패",
	"event.dice.target": "목표 {amount}+",
	"event.result.dice_total": "주사위 합계 {total}",
	"event.result.target": "목표 {amount}",
	"event.result.die_pips": "주사위 눈 {value}",
	"event.result.roulette": "룰렛 {slot}",
	"event.result.card": "전표 {card}",
	"event.roulette.safe": "안전",
	"event.roulette.safe_note": "손실 없음",
	"event.roulette.reward": "소득",
	"event.roulette.reward_note": "코인 획득",
	"event.roulette.risk": "위험",
	"event.roulette.risk_note": "피값 가능",
	"event.action.roll": "굴리기",
	"event.action.spin": "돌리기",
	"event.prop.roll_dice": "주사위 굴리기",
	"event.prop.spin_roulette": "룰렛 돌리기",
	"event.prop.check_slip": "전표 확인",
	"event.prop.open_box": "상자 열기",
	"event.prop.activate": "작동",
	"event.result.default_title": "결과 전표",
	"event.result.default_body": "전표가 닫혔다. 아래 화살표로 맵에 돌아간다.",
	"event.result.closed": "전표가 닫혔다.",
	"event.result.gold": "{delta} 골드",
	"event.result.relic": "유물 {relic}",
	"event.result.next_mod": "다음 전투 보정",
	"event.result.no_change": "변화 없음",
	"event.dice.first": "첫 눈",
	"event.dice.second": "둘째 눈",
	"event.result.dice_fail_title": "판정 실패",
	"event.result.dice_fail_body": "합계가 목표에 닿지 못했다. 전표가 피값을 요구한다.",
	"event.result.dice_success_title": "판정 성공",
	"event.result.dice_success_body": "합계가 목표를 넘겼다. 딜러가 코인을 밀어준다.",
	"event.result.dice_great_title": "대성공",
	"event.result.dice_great_body": "높은 합계가 숨은 봉인을 열었다.",
	"event.result.quiet_exit_title": "조용한 퇴장",
	"event.result.quiet_exit_body": "큰 판은 피했다. 대신 작은 소문값만 챙긴다.",
	"event.result.roulette.empty_title": "빈 칸",
	"event.result.roulette.empty_body": "바퀴가 식었다. 잃은 것도 얻은 것도 없다.",
	"event.result.roulette.small_jackpot_title": "작은 대박",
	"event.result.roulette.small_jackpot_body": "작은 판돈치고는 꽤 크게 맞았다.",
	"event.result.roulette.strong_spin_title": "강한 회전",
	"event.result.roulette.strong_spin_body": "바퀴가 뜨겁게 돌고 코인을 남겼다.",
	"event.result.roulette.safe_hit_title": "안전한 적중",
	"event.result.roulette.safe_hit_body": "무난한 칸에 멈춰 코인을 챙겼다.",
	"event.result.roulette.broken_stake_title": "깨진 판돈",
	"event.result.roulette.broken_stake_body": "바퀴가 붉은 칸에 박히고 피값을 가져갔다.",
	"event.result.roulette.jackpot_title": "대박",
	"event.result.roulette.jackpot_body": "딜러가 숨겨 둔 유물까지 밀어준다.",
	"event.result.roulette.smash_title": "강타 적중",
	"event.result.roulette.smash_body": "위험한 회전이 큰 코인 더미로 돌아왔다.",
	"event.result.roulette.profit_title": "수익 적중",
	"event.result.roulette.profit_body": "좋은 칸에 멈췄다. 전표가 묵직하다.",
	"event.result.roulette.safe_slot_title": "안전 칸",
	"event.result.roulette.safe_slot_body": "크게 터지진 않았지만 손해는 피했다.",
	"event.result.roulette.leave_title": "바퀴를 덮었다",
	"event.result.roulette.leave_body": "판돈을 걸지 않고 작은 코인만 챙긴다.",
	"event.card.coin": "코인 전표",
	"event.card.coin_effect": "+10 골드",
	"event.card.coin_body": "접힌 전표 안에 코인이 묶여 있다.",
	"event.card.blood": "붉은 전표",
	"event.card.blood_effect": "-3 HP, 유물",
	"event.card.blood_body": "피값을 치르자 봉인이 유물 하나를 뱉었다.",
	"event.card.pouch": "작은 주머니",
	"event.card.pouch_effect": "+6 골드",
	"event.card.pouch_body": "큰 일은 없었다. 그래도 코인은 남았다.",
	"event.card.black": "검은 표식",
	"event.card.black_effect": "+18 골드, 다음 피해 +2",
	"event.card.black_body": "큰 돈이지만 다음 상대가 이 표식을 들고 온다.",
	"event.card.heal": "치유 전표",
	"event.card.heal_effect": "+5 HP",
	"event.card.heal_body": "낡은 붕대와 약 냄새가 따라온다.",
	"event.card.hidden_relic": "숨은 유물",
	"event.card.hidden_relic_effect": "유물",
	"event.card.hidden_relic_body": "딜러가 못 본 사이 좋은 전표를 끌어냈다.",
	"event.result.sealed_leave_title": "상자를 닫았다",
	"event.result.sealed_leave_body": "큰 봉인은 건드리지 않고 작은 코인만 챙긴다.",
	"character.default_guard_dice.name": "공격/방어 계약",
	"character.default_guard_dice.subtitle": "고른 눈은 공격, 남은 눈은 방어",
	"character.default_guard_dice.rule_text": "주사위 2개를 굴린다. 하나를 공격에 쓰면 다른 하나가 이번 턴 방어가 된다.",
	"character.double_attack_dice.name": "쌍공격 계약",
	"character.double_attack_dice.subtitle": "메인도 공격, 보조도 공격",
	"character.double_attack_dice.rule_text": "주사위 2개를 굴린다. 하나를 메인 공격으로 고르면 다른 주사위도 공격에 더해진다. 주사위 방어는 없다.",
	"character.black_signer_no_dice.name": "검은 계약자",
	"character.black_signer_no_dice.subtitle": "주사위 대신 계약을 고른다",
	"character.black_signer_no_dice.rule_text": "주사위를 굴리지 않는다. 검/방패/룰렛 계약 중 하나에 서명한다. 빚 표식 3개가 쌓이면 6 피해를 받는다.",
	"character.future_luck_contract.name": "행운 계약",
	"character.future_luck_contract.subtitle": "준비 중",
	"character.future_luck_contract.rule_text": "아직 잠겨 있다.",
	"fallback.none": "없음",
	"fallback.unknown": "알 수 없음"
}

const EN := {
	"brand.title": "Luck Roulette",
	"brand.title_caps": "LUCK ROULETTE",
	"title.tagline": "Bone dice, marked marbles, one crooked wheel.",
	"title.seed": "Run seed  {seed}",
	"title.motto": "HP is life. Gold is leverage.",
	"title.start": "Take a Seat",
	"title.new_run": "New Run",
	"title.continue": "Continue",
	"title.no_save": "No Save",
	"title.gallery": "Gallery",
	"title.settings": "Settings",
	"title.quit": "Quit",
	"title.disabled_hint": "Coming Soon",
	"title.route_note": "The house has dealt today's route.",
	"intro.title": "Taking a Seat",
	"intro.subtitle": "The house lays out this run's route.",
	"intro.progress": "Dealing cards",
	"run_end.clear_title": "Run Clear",
	"run_end.fail_title": "Run Failed",
	"run_end.clear_subtitle": "The final house table folds. The ledger is sealed.",
	"run_end.fail_subtitle": "The table takes its due. This ledger closes here.",
	"run_end.final_hp": "Final HP {hp}/{max_hp}",
	"run_end.gold": "Gold {gold}",
	"run_end.relics": "Relics {count}  {summary}",
	"run_end.nodes_cleared": "Nodes cleared {count}",
	"run_end.last_table": "Last table {name}",
	"run_end.winnings": "Battle reward {amount}",
	"run_end.stats.battle_line": "Battles {battles}  Elites {elites}  Bosses {bosses}",
	"run_end.stats.route_line": "Events {events}  Shops {shops}  Rests {rests}",
	"run_end.stats.character_floor": "Character {character}  Floor {floor}/{max_floor}",
	"run_end.stats.seed": "Seed {seed}",
	"run_end.stats.label.battles": "Battles",
	"run_end.stats.label.nodes": "Nodes",
	"run_end.stats.label.route": "Events",
	"run_end.stats.label.gold": "Gold",
	"run_end.character.default": "Attack/Guard",
	"run_end.character.double_attack": "Double Attack",
	"run_end.restart": "Sit Again",
	"run_end.main_menu": "Main Table",
	"map.title": "LUCK ROUTE",
	"map.subtitle": "dealt cards, dirty links, one table to cheat",
	"map.ledger": "RUN LEDGER",
	"map.hp": "HP {hp}/{max_hp}",
	"map.gold": "Gold {gold}",
	"map.relics": "Relics {count}  {summary}",
	"map.next_mods": "Next mods {count}",
	"map.step": "step {step}",
	"map.choose": "choose {label}",
	"map.state.cleared": "CLEARED",
	"map.state.current": "CURRENT",
	"map.state.house": "HOUSE",
	"map.state.future": "FUTURE",
	"map.node.combat": "TABLE",
	"map.node.elite": "ELITE",
	"map.node.event": "EVENT",
	"map.node.event.chest": "CHEST",
	"map.node.event.quest": "QUEST",
	"map.node.event.gamble": "GAMBLE",
	"map.node.event.mystery": "MYSTERY",
	"map.node.shop": "SHOP",
	"map.node.rest": "REST",
	"map.node.boss": "HOUSE",
	"battle.action.rolling": "Rolling",
	"battle.action.roll": "Roll",
	"battle.action.black_sword": "Sword Contract",
	"battle.action.black_shield": "Shield Contract",
	"battle.action.black_roulette": "Roulette Contract",
	"battle.action.reroll": "Reroll",
	"battle.action.push_dice": "Go",
	"battle.action.confirm": "Stop",
	"battle.action.spin": "Spin",
	"battle.action.place_marble": "Place Marble",
	"battle.action.spinning": "Spinning",
	"battle.action.apply_result": "Apply Result",
	"battle.action.brace": "Brace",
	"battle.action.take": "Take Hit",
	"battle.action.ack": "OK",
	"battle.action.next_turn": "Next Turn",
	"battle.action.stop": "Stop",
	"battle.action.go": "Go",
	"battle.prompt.roll": "Now: roll the dice",
	"battle.prompt.wager": "Now: wager {committed}/{available} marbles, stake {multiplier}",
	"battle.prompt.place_marble_after_dice": "Now: place a marble on the wheel",
	"battle.prompt.marble_landing": "Now: the marble is landing on a wheel slot",
	"battle.prompt.spin": "Now: spin the wheel",
	"battle.prompt.choose_marble_slot": "Now: choose a wheel slot for the marble",
	"battle.prompt.wait_result": "Now: wait for the result",
	"battle.prompt.apply_result": "Now: apply the result",
	"battle.prompt.enemy": "Now: brace for the counter or take it",
	"battle.prompt.run_over": "The table is done. You can start a new one",
	"battle.prompt.next": "Now: continue to the next action",
	"battle.hud.hp": "HP {hp}/{max_hp}",
	"battle.hud.stake": "Stake {amount}",
	"battle.hud.run": "Run {amount}",
	"battle.hud.turn": "Turn {turn}",
	"battle.intent.damage": "Next damage {amount}",
	"battle.intent.guard": "Next guard {amount}",
	"battle.intent.attack_guard": "{damage} damage + {block} guard",
	"battle.intent.buff": "Next damage +{amount}",
	"battle.intent.curse_weak": "Next attack -{amount}",
	"battle.intent.curse_weak_final": "Next final damage {percent}%",
	"battle.intent.curse_mark": "Marked: next damage +{amount}",
	"battle.intent.curse_mark_double": "Marked: next hit x{multiplier}",
	"battle.intent.tax": "Gold -{amount}",
	"battle.intent.attack_tax": "{damage} damage + gold -{amount}",
	"battle.intent.disrupt": "Hide next intent",
	"battle.intent.attack_disrupt": "{damage} damage + hide intent",
	"battle.intent.audit": "Roulette audit",
	"battle.intent.appraise": "Dice appraisal",
	"battle.intent.tithe": "Guard tithe",
	"battle.intent.hidden": "Unknown intent",
	"battle.message.initial": "Dice time. Roll, lock one die, then reroll if needed.",
	"battle.message.encounter": "Dice time. Build this combat's resources first.",
	"battle.message.relics": " Relics: {relics}.",
	"battle.message.opponent": " Opponent: {monster}.",
	"battle.message.start_mods": " {count} starting mods applied.",
	"battle.message.double_attack_prompt": "Choose the main attack die. The other die also adds attack.",
	"battle.message.attack_guard_prompt": "Choose the attack die. The other die becomes guard this turn.",
	"battle.message.black_signer_prompt": "Choose a contract instead of rolling dice. The third debt mark deals damage immediately.",
	"battle.message.black_signer_sword": "Signed the sword contract. Attack {attack}, debt {debt}/3.",
	"battle.message.black_signer_shield": "Signed the shield contract. Attack {attack}, guard {guard}, debt {debt}/3.",
	"battle.message.black_signer_roulette": "Signed the roulette contract. Attack {attack}, bust retry +1, debt {debt}/3.",
	"battle.message.black_signer_debt_hit": "Black debt filled three marks. Lost 6 HP and cleared the marks.",
	"battle.message.double_attack_roll": "Rolled two dice. Choose the main attack die to add both to attack.",
	"battle.message.attack_guard_roll": "Rolled two dice. Choose the attack die; the other becomes guard.",
	"battle.message.double_attack_result": "Dice result {values}. Choose the main attack die to add both to attack.",
	"battle.message.attack_guard_result": "Dice result {values}. Choose the attack die; the other becomes guard.",
	"battle.message.click_spin": "Click the center roulette to spin.",
	"battle.message.click_marble_slot": "Click a roulette slot to place a marble.",
	"battle.message.dice_attack_ready": "Dice pips became attack base {attack}. Send it to the wheel with one marble.",
	"battle.message.roll_single": "Rolled in the left die slot. Attack base {attack}. Reroll or confirm.",
	"battle.message.reroll_choice": "Rerolled. {prompt}",
	"battle.message.reroll_single": "Rerolled only open dice. Attack base {attack}.",
	"battle.message.roll_cup": "Shaking dice in the cup, then rolling onto the battle board.",
	"battle.message.roll_slot": "Rolling dice in the left die slot.",
	"battle.message.dice_result_single": "Dice result {values}. Attack base {attack}. Reroll or confirm.",
	"battle.message.dice_push_success": "Go succeeded from {from} to {to}. Attack base {attack}. {left} Go calls left.",
	"battle.message.dice_push_locked": "Go succeeded from {from} to {to}. Attack base {attack}. Stop now.",
	"battle.message.dice_push_failed": "Go failed from {from} to {to}. New total is halved into attack base {attack}.",
	"battle.message.extra_roll_choice": "Rolled once more. {prompt}",
	"battle.message.extra_roll_single": "Rolled once more. Attack base {attack}.",
	"battle.message.choose_attack_first": "Choose an attack die first.",
	"battle.message.marble_instruction": "Click a roulette slot to place a marble directly. The button places it on the selected slot.",
	"battle.message.marble_boost_slot": "Place a marble on {slot}. If the wheel stops there: {reward}.",
	"battle.message.marble_setup_done": "A marble boosted one roulette slot. Now see the real result in the roulette scene.",
	"battle.message.die_lock": "Die {index} {state}.",
	"battle.message.locked": "locked",
	"battle.message.unlocked": "unlocked",
	"battle.message.attack_guard_selected": "Attack {attack}, guard {guard}. The remaining die became guard.",
	"battle.message.double_attack_selected": "Attack {attack}. Both dice went into attack.",
	"battle.message.marble_scene": "Place the marble directly on a roulette slot in the dedicated scene.",
	"battle.message.marble_slot_selected": "Place a marble on {slot}. This is not the result yet. Spin next.",
	"battle.message.marble_stored": "Kept one {marble} marble for next turn.",
	"battle.message.marble_recalled": "Pulled kept marbles back to hand. You can place them now.",
	"battle.message.roulette_start": "The center roulette spins. The stopped slot becomes this attack multiplier.",
	"battle.message.roulette_return": "Roulette ritual returned to the battle board. Attack multiplier x{multiplier}.",
	"battle.message.roulette_stopped": "Roulette stopped. Apply the result.",
	"battle.message.brake_success": "Brake success. Bust folded into a hit.",
	"battle.message.brake_reduce": "Brake dodged the bust, but the damage multiplier fell.",
	"battle.message.nudge_result": "Nudged the wheel one slot. New result: {slot}",
	"battle.message.double_down": "Double down. Attack multiplier jumps.",
	"battle.message.enemy_action": "{monster} action: {move}. Guard {block}, damage {damage}.",
	"battle.message.turn_start": "Dice time. Build this turn's resources first.",
	"battle.message.cash_out": "Left combat and locked in the payout.",
	"battle.message.marble_ready": "The marble is on the wheel. Now spin the center roulette.",
	"battle.message.wager_ready": "Attack {attack}. Choose how many of {available} combat marbles to wager.",
	"battle.message.wager_changed": "Wagering {committed} marbles. Stake multiplier {multiplier}.",
	"battle.message.numeric_roulette_start": "Locked {committed} marbles. Stake multiplier {wager}. Roulette spins.",
	"battle.message.numeric_roulette_preview": "Roulette {roulette}, stake {wager}. Expected damage {damage}. Stop or go.",
	"battle.message.numeric_go_result": "Go result {roulette}. Current damage {damage}.",
	"battle.message.numeric_damage": "Attack {attack} x roulette {roulette} x stake {wager} = {damage} damage.",
	"battle.banner.attack_marbles": "ATTACK {attack} / marble x{count}",
	"battle.banner.wager": "Set Wager",
	"battle.banner.marble_setting": "Placing Marble",
	"battle.banner.marble_count": "{count} Marble Set",
	"battle.banner.attack_guard": "Attack {attack} / Guard {guard}",
	"battle.banner.attack_no_guard": "Attack {attack} / No Guard",
	"battle.banner.choose_attack_die": "Choose Die",
	"battle.banner.dice_push_success": "Go Win",
	"battle.banner.dice_push_failed": "Go Fail",
	"battle.banner.roulette_start": "Roulette Live",
	"battle.banner.spin_ready": "Spin Roulette",
	"battle.phase.dice": "Dice Turn",
	"battle.phase.wager": "Set Wager",
	"battle.phase.marble": "Place Marble",
	"battle.phase.spinning": "Roulette Spins",
	"battle.phase.intervene": "Last Touch",
	"battle.phase.enemy": "Opponent Turn",
	"battle.phase.win": "Stake Won",
	"battle.phase.end": "Table End",
	"battle.phase.result": "Turn Result",
	"battle.die.left": "Left",
	"battle.die.right": "Right",
	"battle.die.main_attack": "Main Attack",
	"battle.die.attack": "Attack",
	"battle.marble.plain": "Attack",
	"battle.marble.yellow": "Yellow Mark",
	"battle.marble.green": "Green Reward",
	"battle.marble.purple": "Purple Jackpot",
	"battle.layer.multiplier": "x",
	"battle.layer.click_roulette": "Click Roulette",
	"battle.layer.setup_done": "Setup Ready",
	"battle.layer.boosted": "Boosted",
	"battle.layer.rolling_in_cup": "Rolling from Cup",
	"battle.layer.roll_lands_here": "Result lands in this slot",
	"battle.layer.dice_contract": "Dice Contract",
	"battle.layer.attack_value": "Attack {amount}",
	"battle.layer.guard_value": "Guard {amount}",
	"battle.layer.rerolls": "Reroll {amount}",
	"battle.layer.attack_choice": "Choose Attack",
	"battle.layer.reroll_confirm": "Reroll {rerolls} / Confirm",
	"battle.layer.attack_void": "Bust: attack void",
	"battle.layer.apply_result": "Apply Result",
	"battle.layer.bust": "Bust",
	"battle.layer.reward_delta": "Reward {delta}",
	"battle.layer.marble_pouch": "Marble Pouch",
	"battle.layer.slot_boost_count": "Slot boost x{count}",
	"battle.layer.shake_power": "Shake Power",
	"battle.layer.die_pips": "Pips {value}",
	"battle.layer.next": "Next",
	"battle.layer.damage": "Damage {amount}",
	"battle.caption.smirk": "Opponent smirks",
	"battle.caption.hit": "Opponent staggers",
	"battle.caption.press": "Opponent prepares an attack",
	"battle.caption.watch": "Opponent watches the table",
	"roulette.slot.profit.label": "Hit",
	"roulette.slot.profit.hint": "Base multiplier",
	"roulette.slot.profit.banner": "Hit",
	"roulette.slot.jackpot.label": "Jackpot",
	"roulette.slot.jackpot.hint": "Highest multiplier",
	"roulette.slot.jackpot.banner": "Jackpot",
	"roulette.slot.bust.label": "Bust",
	"roulette.slot.bust.hint": "Attack misses",
	"roulette.slot.bust.banner": "Bust",
	"roulette.slot.overdrive.label": "Smash",
	"roulette.slot.overdrive.hint": "High multiplier",
	"roulette.slot.overdrive.banner": "Smash",
	"roulette.slot.safe.label": "Hit",
	"roulette.slot.safe.hint": "Base multiplier",
	"roulette.slot.safe.banner": "Hit",
	"roulette.slot.profit.boost_label": "Hit+",
	"roulette.slot.profit.boost_hint": "Marble raises the multiplier",
	"roulette.slot.profit.boost_banner": "Boosted Hit",
	"roulette.slot.jackpot.boost_label": "Jackpot+",
	"roulette.slot.jackpot.boost_hint": "Marble raises the top multiplier",
	"roulette.slot.jackpot.boost_banner": "Boosted Jackpot",
	"roulette.slot.bust.boost_label": "Bust Guard",
	"roulette.slot.bust.boost_hint": "Marble turns bust into hit",
	"roulette.slot.bust.boost_banner": "Bust Guard",
	"roulette.slot.overdrive.boost_label": "Smash+",
	"roulette.slot.overdrive.boost_hint": "Marble raises the smash multiplier",
	"roulette.slot.overdrive.boost_banner": "Boosted Smash",
	"roulette.slot.safe.boost_label": "Hit+",
	"roulette.slot.safe.boost_hint": "Marble raises the multiplier",
	"roulette.slot.safe.boost_banner": "Boosted Hit",
	"payout.bust": "Roulette {label}. Attack was blocked and an extra penalty applied.",
	"payout.damage": "{boosted}Attack {attack} x{multiplier} = {damage} damage.",
	"payout.boosted_prefix": "Boosted slot! ",
	"payout.bonus": " Bonus payout {delta}.",
	"payout.enemy_blocked": " Enemy guard blocked {amount}.",
	"payout.curse_halved": " Curse cut {before}->{after}.",
	"settings.title": "Settings",
	"settings.subtitle": "Adjust sound, display, and language",
	"settings.master": "Master",
	"settings.bgm": "Music",
	"settings.sfx": "SFX",
	"settings.fullscreen": "Fullscreen",
	"settings.fullscreen_on": "On",
	"settings.language": "Language",
	"settings.language.ko": "한국어",
	"settings.language.en": "English",
	"settings.back": "Back",
	"gallery.title": "Gallery",
	"gallery.category.characters": "Characters",
	"gallery.category.relics": "Relics",
	"gallery.category.monsters": "Monsters",
	"gallery.category.events": "Events",
	"gallery.subtitle.characters": "Contract characters",
	"gallery.subtitle.relics": "Relics found during runs",
	"gallery.subtitle.monsters": "Opponents at the table",
	"gallery.subtitle.events": "Event records",
	"gallery.locked.title": "Locked Page",
	"gallery.locked.body": "No record has been pinned to this page yet.",
	"gallery.undiscovered": "Undiscovered",
	"gallery.status.locked": "Locked",
	"gallery.status.coming_soon": "Coming Soon",
	"gallery.status.needs_art": "Needs Art",
	"gallery.back": "Back",
	"pause.title": "Paused",
	"pause.abandon_title": "Abandon Run",
	"pause.resume": "Resume",
	"pause.return": "Go Back",
	"pause.settings": "Settings",
	"pause.main_menu": "Main Table",
	"pause.abandon": "Abandon Run",
	"pause.confirm_abandon": "Confirm Abandon",
	"pause.phase.map": "The route ledger is covered for a moment.",
	"pause.phase.combat": "The battle table is paused.",
	"pause.phase.reward": "Reward choice is on hold.",
	"pause.phase.event": "Event judgment is on hold.",
	"pause.phase.shop": "Shop trading is paused.",
	"pause.phase.rest": "Rest choice is on hold.",
	"pause.phase.default": "The table is paused.",
	"pause.confirm_label": "Delete this run save and return.",
	"reward.title": "Reward Slip",
	"reward.subtitle": "Take the table reward and choose one run item.",
	"reward.subtitle.claim_all": "Claim everything the table paid out.",
	"reward.winnings": "Battle reward {amount}",
	"reward.claim": "Claim",
	"reward.item.gold": "Gold",
	"reward.item.gold.note": "Base combat payout.",
	"reward.item.tickets": "Tickets",
	"reward.item.tickets.note": "Contract tickets for rest exchange.",
	"reward.item.heal": "Emergency Heal",
	"reward.item.heal.note": "A small low-chance recovery.",
	"reward.item.relic": "Elite Relic",
	"reward.item.relic.note": "Relic payout for elite fights.",
	"reward.choice.money.label": "Gold Pouch",
	"reward.choice.money.note": "Take extra gold.",
	"reward.choice.money.effect": "+{amount} Gold",
	"reward.choice.relic.label": "Relic Claim",
	"reward.choice.relic.note": "Add one run relic.",
	"reward.choice.heal.label": "Stitch Wounds",
	"reward.choice.heal.note": "Patch up behind the table.",
	"reward.choice.heal.effect": "+{amount} HP",
	"rest.upgrade_hint": "Roulette cells cost 1/2/3 vouchers by current value. Roulette costs 1. Dice costs 2.",
	"rest.upgrade.vouchers": "Owned Vouchers {count}",
	"rest.upgrade.effect_cost": "{effect} / Voucher {count}",
	"rest.upgrade.effect_free": "{effect} / Free",
	"rest.upgrade.use_voucher": "Use Voucher ({count})",
	"rest.upgrade.finish": "Finish Upgrade",
	"rest.upgrade.ready_again": "A voucher opened one more upgrade pick.",
	"rest.upgrade.pending_finish": "Finish the upgrade or spend a voucher for one more pick.",
	"rest.back": "Back",
	"rest.action.heal.label": "Bandage Up",
	"rest.action.heal.note": "Stitch the wound, then end the rest.",
	"rest.action.tune.label": "Tune the Table",
	"rest.action.tune.note": "Choose an upgrade that lasts this run.",
	"rest.action.tune.effect": "Choose Upgrade",
	"rest.action.relic.label": "Suspicious Relic",
	"rest.action.relic.note": "Take one covered object.",
	"rest.action.relic.effect": "Relic +1",
	"rest.upgrade.primary.label": "Tune Main Die",
	"rest.upgrade.primary.short": "Main Die",
	"rest.upgrade.primary.note": "Main die interpretation +1.",
	"rest.upgrade.primary.effect": "Main +1",
	"rest.upgrade.secondary.label": "Tune Support Die",
	"rest.upgrade.secondary.short": "Support Die",
	"rest.upgrade.secondary.note": "Support die interpretation +1.",
	"rest.upgrade.secondary.effect": "Support +1",
	"rest.upgrade.roulette.label": "Tune Roulette",
	"rest.upgrade.roulette.note": "All roulette results improve.",
	"rest.upgrade.roulette.effect": "Roulette +0.2x",
	"rest.upgrade.roulette_cell.label": "Upgrade Wheel Cell",
	"rest.upgrade.roulette_cell.note": "Raise one chosen number cell to its next tier.",
	"rest.upgrade.roulette_cell.effect": "Cell vouchers 1-3",
	"rest.upgrade.roulette_cell.title": "Upgrade Wheel Cell",
	"rest.upgrade.roulette_cell.subtitle": "Choose a number cell. x0 and x3 cannot be raised.",
	"rest.upgrade.roulette_cell.vouchers": "Owned Vouchers {count}",
	"rest.upgrade.roulette_cell.cost": "Voucher {count}",
	"rest.upgrade.roulette_cell.max": "Fixed",
	"rest.exchange.open": "Ticket Exchange",
	"rest.exchange.title": "Ticket Exchange",
	"rest.exchange.subtitle": "Spend rest-only contract tickets on potions and small supplies.",
	"rest.exchange.tickets": "Tickets {amount}",
	"rest.exchange.potions": "Potion Slots {used}/{max}",
	"rest.exchange.back_hint": "No exchange yet. You can go back.",
	"rest.exchange.locked_back": "Exchange made. Leaving will end the rest.",
	"rest.exchange.done": "Finish Exchange",
	"rest.exchange.small_heal.label": "Emergency Wrap",
	"rest.exchange.small_heal.note": "Immediate small recovery.",
	"rest.exchange.small_heal.effect": "HP +5",
	"rest.exchange.random_potion.label": "Random Potion",
	"rest.exchange.random_potion.note": "Add a random supply to a potion slot.",
	"rest.exchange.random_potion.effect": "Random Potion +1",
	"rest.exchange.upgrade_voucher.label": "Upgrade Voucher",
	"rest.exchange.upgrade_voucher.note": "A repeatable tuning voucher.",
	"rest.exchange.upgrade_voucher.effect": "Upgrade Voucher +1",
	"rest.exchange.random_relic.label": "Random Relic",
	"rest.exchange.random_relic.note": "Pull one from the current character pool.",
	"rest.exchange.random_relic.effect": "Relic +1",
	"rest.result.heal": "Wounds stitched. +{amount} HP",
	"rest.result.relic": "Took a covered relic. {relic}",
	"rest.result.primary": "Main die tuned. Main interpretation +1 this run",
	"rest.result.secondary": "Support die tuned. Support interpretation +1 this run",
	"rest.result.roulette": "Roulette tuned. All results +0.2x this run",
	"rest.result.roulette_cell": "Wheel cell upgraded. {from} -> {to}",
	"rest.result.exchange": "Exchanged {tickets} tickets. Potions +{potions}",
	"rest.result.done": "Rest action complete.",
	"shop.confirm": "Confirm Buy",
	"shop.storage": "Storage",
	"shop.prep.label": "Prep Mark",
	"shop.prep.note": "Reduce the next combat hit.",
	"shop.prep.effect": "Next damage -2",
	"shop.gold_price": "{amount} Gold",
	"shop.ticket_price": "{amount} Tickets",
	"shop.insufficient": "Short",
	"shop.detail.title": "Offer Slip",
	"shop.detail.empty": "Choose an item on display.",
	"shop.detail.empty_note": "Description and buy button open here.",
	"shop.no_selection": "No Selection",
	"shop.product_fallback": "Goods",
	"shop.prep.description": "Softens the first enemy hit next combat.",
	"shop.visit_bought": "Bought {count}",
	"shop.reroll": "Reroll",
	"shop.reroll_price": "{amount} Gold",
	"shop.service.soft_prep.label": "Prep Mark",
	"shop.service.soft_prep.note": "Reduce the next combat hit.",
	"shop.service.soft_prep.effect": "Next damage -2",
	"shop.service.soft_prep.description": "Reduce the first enemy hit next combat by 2.",
	"shop.service.cash_bait.label": "Cash Bait",
	"shop.service.cash_bait.note": "Raise the next stakes.",
	"shop.service.cash_bait.effect": "Next reward +8",
	"shop.service.cash_bait.description": "Increase next combat reward gold by 8.",
	"shop.service.heal_vial.label": "Red Cure Vial",
	"shop.service.heal_vial.note": "Patch the wounds quickly.",
	"shop.service.heal_vial.effect": "HP +8",
	"shop.service.heal_vial.description": "Recover 8 HP, up to max HP.",
	"shop.service.marble_polish.label": "Marble Polish",
	"shop.service.marble_polish.note": "Buff wager marbles.",
	"shop.service.marble_polish.effect": "Wager Polish +1",
	"shop.service.marble_polish.description": "Committed wager marbles gain more value this run.",
	"shop.service.dice_tune.label": "Dice Tune",
	"shop.service.dice_tune.note": "File the main die.",
	"shop.service.dice_tune.effect": "Main read +1",
	"shop.service.dice_tune.description": "Main die interpretation is increased by 1 this run.",
	"shop.service.roulette_tune.label": "Wheel Tune",
	"shop.service.roulette_tune.note": "Loosen the wheel reading.",
	"shop.service.roulette_tune.effect": "Result +0.2x",
	"shop.service.roulette_tune.description": "Roulette result bonus is increased by 0.2 this run.",
	"shop.service.risk_contract.label": "Risk Contract",
	"shop.service.risk_contract.note": "More payout, more teeth.",
	"shop.service.risk_contract.effect": "Reward +14 / damage +2",
	"shop.service.risk_contract.description": "Next combat pays more, but enemy damage also rises by 2.",
	"shop.service.blood_discount.label": "Blood Coupon",
	"shop.service.blood_discount.note": "A slip paid in blood.",
	"shop.service.blood_discount.effect": "HP -3 / reward +10",
	"shop.service.blood_discount.description": "Lose 3 HP and increase next combat reward gold by 10.",
	"table.pickup.waiting": "Waiting",
	"table.pickup.waiting_line": "Choose a card to pin its result to the ledger or tray.",
	"table.pickup.gold_loss": "Gold {old} -> {new} ({delta})",
	"table.pickup.gold_gain": "Gold +{delta} -> {new}",
	"table.pickup.ticket_loss": "Tickets {old} -> {new} ({delta})",
	"table.pickup.ticket_gain": "Tickets +{delta} -> {new}",
	"table.pickup.hp_loss": "HP {old} -> {new}/{max} ({delta})",
	"table.pickup.hp_gain": "HP +{delta} -> {new}/{max}",
	"table.pickup.relic_added": "{relic} added",
	"table.pickup.prep": "Prep: {description}",
	"table.pickup.potion_added": "Potion: {potion}",
	"table.pickup.potion_removed": "Used: {potion}",
	"table.pickup.no_change": "No change",
	"battle.action.potion": "Potion",
	"battle.action.back": "Back",
	"battle.message.potion.red": "Red potion: restored {amount} damage from the previous turn.",
	"battle.message.potion.guard": "Yellow shield potion: gained 10 block.",
	"battle.message.potion.reward": "Green potion: victory reward chances are doubled.",
	"battle.message.potion.jackpot": "Purple lightning potion: first jackpot this combat deals +30 damage.",
	"battle.message.potion.wager": "White potion: gained 2 plain wager marbles.",
	"battle.message.potion.time": "Cyan potion: gained 1 extra Go chance.",
	"potion.red_recovery_potion": "Red Recovery Potion",
	"potion.reward_luck_potion": "Green Reward Potion",
	"potion.jackpot_potion": "Purple Lightning Potion",
	"potion.dice_potion": "Blue Dice Potion",
	"potion.time_potion": "Cyan Time Potion",
	"potion.attack_potion": "Attack Potion",
	"potion.guard_potion": "Guard Potion",
	"potion.roulette_potion": "Roulette Potion",
	"potion.wager_potion": "Wager Potion",
	"potion.upgrade_voucher": "Upgrade Voucher",
	"table.choice.money": "Gold Settled",
	"table.choice.relic": "Relic Gained",
	"table.choice.heal": "Healing Settled",
	"table.choice.shop_relic": "Shop Relic",
	"table.choice.prep": "Prep Note",
	"table.choice.event_gold": "Rumor Payout",
	"table.choice.event_relic_trade": "Relic Trade",
	"table.choice.event_risk_gold": "Hot Deal",
	"table.choice.backroom_die_test": "Backroom Dice",
	"table.choice.backroom_die_leave": "Quiet Exit",
	"table.choice.crooked_wheel_bet": "Crooked Wheel",
	"table.choice.crooked_wheel_leave": "Declined Wheel",
	"table.choice.sealed_side_box": "Sealed Slip",
	"table.choice.sealed_cards_leave": "Closed Box",
	"table.choice.rest_heal": "Rest Heal",
	"table.choice.rest_leave": "Leave Rest",
	"table.choice.rest_ticket_exchange": "Ticket Exchange",
	"table.choice.ticket_random_potion": "Random Potion Exchange",
	"table.choice.ticket_upgrade_voucher": "Upgrade Voucher Exchange",
	"table.choice.ticket_small_heal": "Wrap Exchange",
	"table.choice.ticket_random_relic": "Random Relic Exchange",
	"table.choice.combat_reward": "Combat Reward",
	"table.choice.elite_reward": "Elite Reward",
	"table.choice.result": "Result Settled",
	"table.prep.damage_up": "Next damage +{amount}",
	"table.prep.damage_down": "Next damage -{amount}",
	"table.prep.default": "next combat note",
	"overlay.exit": "Exit",
	"overlay.relics": "Relics",
	"overlay.hp": "HP",
	"overlay.gold": "Gold",
	"overlay.tickets": "Tickets",
	"overlay.potions": "Potion",
	"overlay.floor": "Floor",
	"overlay.settings": "Settings",
	"overlay.empty": "Empty",
	"overlay.result_settled": "Result Settled",
	"overlay.relic_tray": "Relic Tray",
	"overlay.prep_notes": "Prep Notes",
	"overlay.applied_notes": "Applied Notes",
	"overlay.no_pending": "None queued",
	"character.select.title": "Choose Contract",
	"character.select.hint": "Press a card to preview it, then start the contract.",
	"character.select.selected": "Selected",
	"character.select.confirm": "Start Contract",
	"character.starting_relic.label": "Starting Relic",
	"ritual.enemy.default_intent": "The opponent is lining up a move",
	"ritual.enemy.apply": "Apply Enemy\nTo Result",
	"ritual.resolution.default_message": "Apply the result.",
	"ritual.resolution.formula": "Multiply dice attack by the roulette multiplier and apply damage",
	"ritual.resolution.return_note": "Send the result back to the battle board",
	"ritual.resolution.apply": "Apply Result\nTo Battle",
	"event.fallback.title": "Event Slip",
	"event.story.show_choices": "Show Choices",
	"event.story.next_slip": "Next Slip",
	"event.header.dice_title": "Backroom Dice Check",
	"event.header.dice_subtitle": "Beat the target with the sum of two dice.",
	"event.header.roulette_title": "Crooked Roulette",
	"event.header.roulette_subtitle": "The stopped slot closes the slip.",
	"event.header.card_title": "Sealed Slip Draw",
	"event.header.card_subtitle": "Choose one card. The slip closes when it flips.",
	"event.dice.great": "Great",
	"event.dice.success": "Success",
	"event.dice.fail": "Fail",
	"event.dice.target": "Target {amount}+",
	"event.result.dice_total": "Dice total {total}",
	"event.result.target": "Target {amount}",
	"event.result.die_pips": "Die pips {value}",
	"event.result.roulette": "Roulette {slot}",
	"event.result.card": "Slip {card}",
	"event.roulette.safe": "Safe",
	"event.roulette.safe_note": "No loss",
	"event.roulette.reward": "Payout",
	"event.roulette.reward_note": "Gain coins",
	"event.roulette.risk": "Risk",
	"event.roulette.risk_note": "HP cost possible",
	"event.action.roll": "Roll",
	"event.action.spin": "Spin",
	"event.prop.roll_dice": "Roll Dice",
	"event.prop.spin_roulette": "Spin Roulette",
	"event.prop.check_slip": "Check Slip",
	"event.prop.open_box": "Open Box",
	"event.prop.activate": "Use",
	"event.result.default_title": "Result Slip",
	"event.result.default_body": "The slip is closed. Use the arrow below to return to the map.",
	"event.result.closed": "The slip closed.",
	"event.result.gold": "{delta} Gold",
	"event.result.relic": "Relic {relic}",
	"event.result.next_mod": "Next combat mod",
	"event.result.no_change": "No change",
	"event.dice.first": "First Die",
	"event.dice.second": "Second Die",
	"event.result.dice_fail_title": "Check Failed",
	"event.result.dice_fail_body": "The total missed the target. The slip demands a blood price.",
	"event.result.dice_success_title": "Check Passed",
	"event.result.dice_success_body": "The total beat the target. The dealer pushes coins forward.",
	"event.result.dice_great_title": "Great Success",
	"event.result.dice_great_body": "The high total opened a hidden seal.",
	"event.result.quiet_exit_title": "Quiet Exit",
	"event.result.quiet_exit_body": "You dodged the big table and kept a small rumor payout.",
	"event.result.roulette.empty_title": "Empty Slot",
	"event.result.roulette.empty_body": "The wheel cooled. Nothing lost, nothing gained.",
	"event.result.roulette.small_jackpot_title": "Small Jackpot",
	"event.result.roulette.small_jackpot_body": "A small stake paid better than expected.",
	"event.result.roulette.strong_spin_title": "Strong Spin",
	"event.result.roulette.strong_spin_body": "The wheel ran hot and left coins behind.",
	"event.result.roulette.safe_hit_title": "Safe Hit",
	"event.result.roulette.safe_hit_body": "It stopped on a clean slot. You take the coins.",
	"event.result.roulette.broken_stake_title": "Broken Stake",
	"event.result.roulette.broken_stake_body": "The wheel bit into a red slot and took blood.",
	"event.result.roulette.jackpot_title": "Jackpot",
	"event.result.roulette.jackpot_body": "The dealer slides out a hidden relic too.",
	"event.result.roulette.smash_title": "Smash Hit",
	"event.result.roulette.smash_body": "The risky spin came back as a heavy coin pile.",
	"event.result.roulette.profit_title": "Profit Hit",
	"event.result.roulette.profit_body": "A good slot. The slip feels heavy.",
	"event.result.roulette.safe_slot_title": "Safe Slot",
	"event.result.roulette.safe_slot_body": "Not huge, but no loss.",
	"event.result.roulette.leave_title": "Covered the Wheel",
	"event.result.roulette.leave_body": "No stake placed. You only take the small coins.",
	"event.card.coin": "Coin Slip",
	"event.card.coin_effect": "+10 Gold",
	"event.card.coin_body": "Coins are tied inside the folded slip.",
	"event.card.blood": "Red Slip",
	"event.card.blood_effect": "-3 HP, Relic",
	"event.card.blood_body": "The seal spits out a relic after the blood price.",
	"event.card.pouch": "Small Pouch",
	"event.card.pouch_effect": "+6 Gold",
	"event.card.pouch_body": "Nothing dramatic. Still, coins remain.",
	"event.card.black": "Black Mark",
	"event.card.black_effect": "+18 Gold, next damage +2",
	"event.card.black_body": "Good money, but the next opponent carries this mark.",
	"event.card.heal": "Healing Slip",
	"event.card.heal_effect": "+5 HP",
	"event.card.heal_body": "Old bandages and medicine scent follow it.",
	"event.card.hidden_relic": "Hidden Relic",
	"event.card.hidden_relic_effect": "Relic",
	"event.card.hidden_relic_body": "You pull a good slip while the dealer misses it.",
	"event.result.sealed_leave_title": "Closed the Box",
	"event.result.sealed_leave_body": "You leave the big seal alone and take small coins.",
	"character.default_guard_dice.name": "Attack/Guard Contract",
	"character.default_guard_dice.subtitle": "Chosen die attacks, the other guards",
	"character.default_guard_dice.rule_text": "Roll two dice. Use one for attack; the other becomes guard for this turn.",
	"character.double_attack_dice.name": "Double Attack Contract",
	"character.double_attack_dice.subtitle": "Main die attacks, support die attacks too",
	"character.double_attack_dice.rule_text": "Roll two dice. Choose one as the main attack die; the other die also adds attack. Dice guard is zero.",
	"character.black_signer_no_dice.name": "Black Signer",
	"character.black_signer_no_dice.subtitle": "Choose contracts instead of rolling dice",
	"character.black_signer_no_dice.rule_text": "No dice roll. Sign sword, shield, or roulette contracts. At 3 debt marks, take 6 damage.",
	"character.future_luck_contract.name": "Luck Contract",
	"character.future_luck_contract.subtitle": "Coming soon",
	"character.future_luck_contract.rule_text": "Still locked.",
	"fallback.none": "none",
	"fallback.unknown": "unknown"
}

const STRINGS := {
	"ko": KO,
	"en": EN
}

static func t(key: String, params: Dictionary = {}) -> String:
	var locale := current_locale()
	var table: Dictionary = STRINGS.get(locale, KO)
	var fallback: Dictionary = STRINGS.get(DEFAULT_LOCALE, KO)
	var template: String = str(table.get(key, fallback.get(key, "[[" + key + "]]")))
	for param_key in params.keys():
		template = template.replace("{" + str(param_key) + "}", str(params[param_key]))
	if template == "":
		return "[[" + key + "]]"
	return template

static func has(key: String) -> bool:
	var table: Dictionary = STRINGS.get(current_locale(), KO)
	return table.has(key) or KO.has(key)

static func current_locale() -> String:
	return normalize_locale(TranslationServer.get_locale())

static func set_locale(locale: String) -> void:
	TranslationServer.set_locale(normalize_locale(locale))

static func normalize_locale(locale: String) -> String:
	var clean := locale.strip_edges().to_lower()
	if clean.begins_with("en"):
		return "en"
	if clean.begins_with("ko"):
		return "ko"
	return DEFAULT_LOCALE
